server:
  port: 8080
spring:
  application:
    name: LicenciApp
  data:
    mongodb:
      database: db_licenciapp
      username: root
      password: mongodbpass1
      port: 27017
      authentication-database: admin
      auto-index-creation: true
  threads:
    virtual:
      enabled: true
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-doc/swagger-ui.html # URL: http://localhost:8080/swagger-doc/webjars/swagger-ui/index.html
logging:
  level:
    pe.marcolopez.apps.licenciapp: warn
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug
custom:
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a300
    expire-duration: 5