version: "3.8"

services:
  mongo-db-lapp:
    image: mongo
    container_name: mongo-db-lapp
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodbpass1
      MONGO_INITDB_DATABASE: db_licenciapp
    networks:
      - default
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express-lapp:
    image: mongo-express
    container_name: mongo-express-lapp
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongodbpass1
      - ME_CONFIG_MONGODB_URL=mongodb://root:mongodbpass1@mongo-db-lapp:27017/db_licenciapp?authSource=admin
    depends_on:
      - mongo-db-lapp
    networks:
      - default

networks:
  default:
    name: licenciapp-net
